suzuki-shunsuke/go-graylog

- Gopkg.lock
- mockserver/handler/alert_condition.go
- mockserver/handler/handler.go
- mockserver/handler/index_set.go
- mockserver/handler/index_set_stats.go
- mockserver/handler/input.go
- mockserver/handler/not_found.go
- mockserver/handler/params.go
- mockserver/handler/role.go
- mockserver/handler/role_member.go
- mockserver/handler/router.go
- mockserver/handler/stream.go
- mockserver/handler/stream_rule.go
- mockserver/handler/user.go
- mockserver/logic/role.go
httprouter's pattern matching is difficult.
julienschmidt/httprouter#175
> reafactor: replace httprouter into echo

- .git-rm-branch.yml
- alert.go
- alert_condition.go
- client/alert.go
- client/alert_test.go
- client/endpoint/alert.go
- client/endpoint/alert_condition.go
- client/endpoint/alert_test.go
- client/endpoint/endpoint.go
- client/index_set.go
- client/role_test.go
- input_attrs_test.go
- mockserver/exec/main.go
- mockserver/handler/alert.go
- mockserver/handler/router.go
- mockserver/logic/alert.go
- mockserver/logic/alert_test.go
- mockserver/store/plain/alert.go
- mockserver/store/plain/alert_test.go
- mockserver/store/plain/store.go
- mockserver/store/store.go
GET /streams/alerts Get the most recent alarms of all streams
> feat: support GET Alerts API

- README.md
- client/dashboard.go
- client/dashboard_test.go
- client/endpoint/dashboard.go
- client/endpoint/dashboard_test.go
- client/endpoint/endpoint.go
- client/stream_test.go
- dashboard.go
- docker-compose.yml.tmpl
- mockserver/handler/dashboard.go
- mockserver/handler/router.go
- mockserver/logic/dashboard.go
- mockserver/store/plain/dashboard.go
- mockserver/store/plain/store.go
- mockserver/store/store.go
- terraform/README.md
- terraform/docs/dashboard.md
- terraform/graylog/provider.go
- terraform/graylog/resource_dashboard.go
- terraform/graylog/resource_dashboard_test.go
- terraform/graylog/resource_user.go
- terraform/graylog/resource_user_test.go
- testutil/test_data.go
Closes: https://github.com/suzuki-shunsuke/go-graylog/issues/18
> feat: support dashboard api

- .circleci/config.yml
- Gopkg.lock
- client/dashboard_widget_test.go
- dashboard.go
- testutil/test_data.go
* fix Timerange.Type
* change Widget.CacheTime to pointer
**BREAKING CHANGE: change Widget.CacheTime's type**
> fix: fix dashboard widget api

- terraform/README.md
* https://github.com/suzuki-shunsuke/example/tree/master/graylog-terraform
* https://hub.docker.com/r/suzukishunsuke/terraform-graylog
> docs: add links to example and docker-image-terraform-graylog

- terraform/README.md
- terraform/docs/stream_rule.md
- terraform/graylog/provider.go
- terraform/graylog/resource_stream_rule.go
- terraform/graylog/resource_stream_rule_test.go
> feat: support terraform resource stream_rule

- terraform/docs/stream_rule.md
- terraform/graylog/resource_stream_rule.go
> feat: support terraform import of stream rule

- terraform/graylog/resource_alarm_callback.go
- terraform/graylog/resource_alert_condition.go
- terraform/graylog/resource_index_set.go
- terraform/graylog/resource_input.go
- terraform/graylog/util.go
> fix: fix error handling of terraform provider

- .circleci/config.yml
- .gometalinter.json
- client/endpoint/endpoint.go
- client/endpoint/pipeline_rule.go
- client/pipeline_rule.go
- client/pipeline_rule_test.go
- pipeline_rule.go
- scripts/lint.sh
- terraform/README.md
- terraform/docs/pipeline_rule.md
- terraform/graylog/provider.go
- terraform/graylog/resource_pipeline_rule.go
- terraform/graylog/util.go
> Support pipeline rule API

- .drone.yml
- .golangci.yml
- CONTRIBUTING.md
- package.json
- scripts/build.sh
- scripts/commitlint-circleci.sh
- scripts/drone-local-env
- scripts/lint.sh
- scripts/release.sh
- scripts/upload.sh
* replace CircleCI to Drone
* replace gometalinter to golangci-lint
> ci: replace CircleCI to Drone

- .drone.yml
https://cloud.drone.io/suzuki-shunsuke/go-graylog/18/2/1
> ci: update Docker image for gox

- terraform/graylog/resource_alert_condition.go
> feat: support terraform import of Alert Condition

- terraform/docs/alert_condition.md
- terraform/graylog/resource_alert_condition.go
> fix: add repeat_notifications to terraform's alert condition resource

- .drone.yml
- .golangci.yml
- package-lock.json
* build: sort linters
* build: update npm pacakges
* ci: upgrade docker images
```console
$ npm i
audited 1910 packages in 7.72s
found 7 vulnerabilities (3 moderate, 4 high)
run `npm audit fix` to fix them, or `npm audit` for details
$ npm audit fix
added 1 package, removed 1 package and updated 4 packages in 1.691s
fixed 7 of 7 vulnerabilities in 1910 scanned packages
```
> build: update npm packages and docker images and sort linters

- client/endpoint/endpoint.go
- client/endpoint/pipeline.go
- client/pipeline.go
- client/pipeline_test.go
- pipeline.go
- terraform/README.md
- terraform/docs/pipeline.md
- terraform/graylog/provider.go
- terraform/graylog/resource_pipeline.go
> feat: support Plugins/Pipelines/Pipelines API

- index_set.go
- terraform/graylog/resource_index_set.go
> feat: add the field "field_type_refresh_interval" to IndexSet

- terraform/graylog/resource_input.go
> fix: fix import of input

- input_attrs.go
- input_raw_kafka.go
> fix: add the input type InputTypeRawKafka

- terraform/graylog/resource_alarm_callback.go
- terraform/graylog/resource_alert_condition.go
- terraform/graylog/resource_pipeline_connection.go
- terraform/graylog/resource_stream.go
- terraform/graylog/resource_stream_rule.go
Close #101
* graylog_stream_rule's stream_id
* graylog_alarm_callback's stream_id
* graylog_alert_condition's stream_id
* graylog_pipeline_condition's stream_id
> fix: make some terraform resource fields's ForceNew true

- Gopkg.lock
- client/endpoint/extractor.go
- client/extractor.go
- client/extractor_test.go
- extractor.go
- extractor_test.go
- terraform/README.md
- terraform/docs/extractor.md
- terraform/graylog/provider.go
- terraform/graylog/resource_extractor.go
> feat: support Extractor API

- README.md
> docs: #66 update README

- go.mod
- terraform/README.md
- terraform/docs/data_source_index_set.md
- terraform/graylog/data_source_index_set.go
- terraform/graylog/provider.go
- terraform/graylog/resource_index_set.go
> feat: support data source of graylog_index_set

- terraform/README.md
- terraform/docs/data_source_stream.md
- terraform/graylog/data_source_stream.go
- terraform/graylog/provider.go
- terraform/graylog/resource_stream.go
> feat: add the data source of graylog_stream

- client/endpoint/input_static_fields.go
- client/input_static_field.go
- terraform/README.md
- terraform/docs/input_static_fields.md
- terraform/graylog/provider.go
- terraform/graylog/resource_input_static_fields.go
> feat: support StaticFields API

- .gitignore
- terraform/README.md
A small PR with some documentation fixes.
It took me some time when I was trying to play with old version and old docker image ;-).
Thank you for your work!
> Some doc fixes

- .drone.yml
- .durl.yml
- package.json
- scripts/durl.sh
https://github.com/suzuki-shunsuke/durl
> build: use durl

- alert.go
- client/dashboard_widget.go
- client/dashboard_widget_test.go
- client/endpoint/dashboard_widget.go
- collector_configuration.go
- dashboard.go
- dashboard_test.go
- go.sum
- index_set.go
- input.go
- input_attrs.go
- input_data.go
- pipeline.go
- role.go
- stream.go
- stream_rule.go
- terraform/README.md
- terraform/docs/dashboard_widget.md
- terraform/graylog/provider.go
- terraform/graylog/resource_dashboard_widget.go
- terraform/graylog/util.go
- testutil/test_data.go
- user.go
Close #20 
BREAKING_CHANGE: the type of DashboardWidget and Widget.Config change
> feat: add the terraform resource "graylog_dashboard_widget"

- terraform/docs/stream.md
https://github.com/suzuki-shunsuke/go-graylog/issues/127#issuecomment-509035625
> docs: add the optional parameter "description" to the stream

- terraform/docs/dashboard_widget_positions.md
spelling in graylog_dashboard_widget_positions
> spelling in graylog_dashboard_widget_positions

- terraform/graylog/resource_alarm_callback.go
- terraform/graylog/resource_alert_condition.go
> fix: fix how to set the value to terraform's TypeMap field

- .drone.yml
> fix: build the binary with the environment variable CGO_ENABLED=0

- .envrc
- alert_condition.go
>  fix: remove "omitempty" from repeat_notifications

- alert_condition.go
- client/ldap_setting_test.go
- dashboard_widget.go
- index_set.go
- input.go
- input_aws_flow_logs.go
- input_aws_logs.go
- input_beats.go
- input_cef_amqp.go
- input_cef_kafka.go
- input_cef_tcp.go
- input_cef_udp.go
- input_cloud_trail.go
- input_data.go
- input_fake_http_message.go
- input_gelf_amqp.go
- input_gelf_http.go
- input_gelf_kafka.go
- input_gelf_tcp.go
- input_json_path.go
- input_raw_amqp.go
- input_raw_kafka.go
- input_syslog_amqp.go
- input_syslog_kafka.go
- input_syslog_udp.go
- ldap_setting.go
- role.go
- stream.go
- stream_rule.go
- user.go
> fix: remove "omitempty" from bool fields

- client/endpoint/endpoint.go
- client/endpoint/grok_pattern.go
- client/grok_pattern.go
- client/grok_pattern_test.go
- go.mod
- go.sum
- grok_pattern.go
- terraform/docs/grok_pattern.md
- terraform/example/v0.12/grok_pattern.tf
- terraform/graylog/provider.go
- terraform/graylog/resource_grok_pattern.go
issue: #156
Note that currently this resource doesn't support content packs.
> feat: support Grok pattern API

- client/stream_rule.go
- client/stream_rule_test.go
- stream_rule.go
```
GET /streams/{streamid}/rules/typesGet all available stream types
```
> feat: support to get stream rule types

- terraform/README.md
- terraform/docs/data_source_dashboard.md
- terraform/example/v0.12/dashboard.tf
- terraform/graylog/data_source_dashboard.go
- terraform/graylog/provider.go
- terraform/graylog/resource_dashboard.go
https://github.com/suzuki-shunsuke/go-graylog/issues/109#issuecomment-538131946
> feat: support data_source_dashboard

- terraform/docs/extractor.md
- terraform/example/v0.12/alarm_callback.tf
- terraform/example/v0.12/extractor.tf
- terraform/example/v0.12/input.tf
- terraform/graylog/resource_extractor.go
> Fix extractor: make date_format optional and fix panic

- client/endpoint/endpoint.go
- client/endpoint/output.go
- client/output.go
- client/output_test.go
- cmd/generate-testdata/main.go
- output.go
- stream.go
- terraform/README.md
- terraform/docs/output.md
- terraform/example/v0.12/docker-compose.yml
- terraform/example/v0.12/output.tf
- terraform/graylog/provider.go
- terraform/graylog/resource_output.go
- testdata/gelf_output.json
- testdata/outputs.go
- testdata/outputs.json
- testdata/stdout_output.go
- testdata/stdout_output.json
issue: https://github.com/suzuki-shunsuke/go-graylog/issues/191
> feat: support system/outputs API

- client/endpoint/stream_output.go
- client/stream_output.go
- client/stream_output_test.go
- terraform/.gitignore
- terraform/README.md
- terraform/docs/stream_output.md
- terraform/example/v0.12/dashboard.tf
- terraform/example/v0.12/stream_output.tf
- terraform/example/v0.12/terraform.tfvars
- terraform/graylog/provider.go
- terraform/graylog/resource_stream_output.go
- testdata/request_create_stream_outputs.json
issue: https://github.com/suzuki-shunsuke/go-graylog/issues/191
> feat: support /streams/{streamid}/outputs API

- client/endpoint/endpoint.go
- client/endpoint/event_notification.go
- client/event_notification.go
- client/event_notification_test.go
- cmd/generate-testdata/main.go
- event_notification.go
- terraform/README.md
- terraform/docs/event_notification.md
- terraform/example/v0.12/docker-compose.yml
- terraform/example/v0.12/event_notification.tf
- terraform/graylog/provider.go
- terraform/graylog/resource_event_notification.go
- testdata/event_notifications.go
- testdata/event_notifications.json
- testdata/request_create_event_notification.go
- testdata/request_create_event_notification.json
- testdata/response_create_event_notification.go
- testdata/response_create_event_notification.json
https://github.com/suzuki-shunsuke/go-graylog/issues/170
> feat: support Event Notification

- terraform/example/v0.12/event_definition.tf
- terraform/graylog/resource_event_definition.go
https://github.com/suzuki-shunsuke/go-graylog/issues/170#issuecomment-563663440
> fix: fix the bug of Event Definition

- terraform/graylog/resource_event_definition.go
https://github.com/suzuki-shunsuke/go-graylog/issues/170#issuecomment-565188479
Sort `.config.streams` before checking diff
> fix: fix DiffSuppressFunc of EventDefinition's config

- .cmdx.yaml
- .drone.yml
- scripts/jsonlint.sh
* https://github.com/cytopia/docker-jsonlint
* https://github.com/zaach/jsonlint
* https://www.npmjs.com/package/jsonlint
> ci: use jsonlint

- input_attrs.go
- input_data.go
- input_raw_tcp.go
- input_unknown_attrs.go
- terraform/example/v0.12/input.tf
> fix: fix a bug of InputUnknownAttrs

- client/dashboard_widget_test.go
- dashboard_widget_test.go
- terraform/graylog/resource_dashboard_widget.go
- testdata/dashboard_widget.go
- testdata/dashboard_widget/stacked_chart/create.json
- testdata/dashboard_widget/stacked_chart/create.tf
- testdata/dashboard_widget/stacked_chart/get.json
- testdata/dashboard_widget/stacked_chart/update.json
- testdata/dashboard_widget/stacked_chart/update.tf
https://github.com/suzuki-shunsuke/go-graylog/issues/227
> fix: support to update Dashboard Widget

- terraform/graylog/resource_dashboard_widget.go
- terraform/graylog/util.go
https://github.com/suzuki-shunsuke/go-graylog/issues/230
> fix: set blank id when it is failed to get a dashboard widget

- terraform/graylog/resource_stream.go
- terraform/graylog/resource_stream_test.go
- testdata/stream/update.tf
- testdata/stream/updated_stream.json
https://github.com/suzuki-shunsuke/go-graylog/issues/232
> fix: update the graylog_stream's disabled attribute

- terraform/example/v0.12/role.tf
- terraform/example/v0.12/user.tf
https://github.com/suzuki-shunsuke/go-graylog/issues/236
> docs: add an example

- graylog/client/endpoint/user.go
- graylog/client/user_token.go
- graylog/client/user_token_test.go
- graylog/graylog/user_token.go
issue: https://github.com/suzuki-shunsuke/go-graylog/issues/244
> feat: support user token API

- graylog/client/event_definition.go
- graylog/graylog/event_definition.go
- graylog/terraform/resource_event_definition.go
issue: https://github.com/suzuki-shunsuke/go-graylog/issues/247
> feat: support key_spec of EventDefinition

- examples/v0.12/extractor.tf
- graylog/graylog/extractor.go
- graylog/terraform/resource_extractor.go
issue: https://github.com/suzuki-shunsuke/go-graylog/issues/251
> feat: support extractor type "split_and_index"

- examples/v0.12/dashboard.tf
- examples/v0.12/event_definition.tf
- examples/v0.12/event_notification.tf
- examples/v0.12/output.tf
[jsonencode](https://www.terraform.io/docs/configuration/functions/jsonencode.html)
* Validate the parameter
* IDE can validate and format the parameter. Here document is a just string, so IDE can't validate and format the content.
> docs: refactor example using jsonencode

- docs/resources/user.md
- graylog/graylog/user.go
- graylog/terraform/resource_user.go
#304 
BREAKING CHANGE: change session_timeout_ms's computed to false
> fix: set the default value of user's session_timeout_ms
